### ISSUE TITLE
Python 3 support with xtea3

### ISSUE THREAD

**Issue by Varbin** [Varbin/xtea#5]

**Comment by theStack** [comment]
Is development of xtea3 still active?
I've looked into the module trying to make it Python 3 compatible, the following steps were needed:
- remove the 'L' suffix from constants in methods `_encrypt` and `_decrypt`, as this is not valid in Python 3 anymore (not sure though if it hurts if missing in Python 2.x)
- replace all '/' operators with '//' (floor division, available since Python 2.2)
- put parantheses around ordinary print statements
- rewrite print statements directing output to stderr (e.g. sys.stderr.write("foobar\n") which both works in Python 2 and 3)
- define a dummy function for ord() just returning the passed value if we use Python 3, e.g.:

`
if sys.version_info.major >= 3:
    def ord(c):
        return c
`

- use `b"".join(...)` instead of `"".join(...)` in methods `encrypt` and `decrypt` to create byte strings
- let both functions `xor_strings` and `_crypt_ofb` return a byte string rather than a string by applying `.encode("latin-1")` to the return value (this unfortunately breaks compatibility with Python 2)
- replace `long` by `int` in function `stringToLong` (long doesn't exist anymore in Python 3)
- replacing `types.IntType, types.LongType, types.FloatType` with `int, int, float`, respectively

**Comment by Varbin** [comment]
xtea3 is even working (https://github.com/Varbin/xtea3) but not working with python 3.  

But I think it's better to have one codebase for both, too.

By the way: Why does `.encode("latin-1")` break compatibility in Python2? In Python 2 the function will return a string ( an encoded string is still a string) and on Python 3 it should return bytes.

**Comment by Varbin** [comment]
Thank you for your contribution, I added many of your ideas to the code.

Instead of using dummy ord, I defined `b_ord` and `b_chr`.

**Comment by chrisrossi** [comment]
Any possibility of a release to get Python 3 support?  Tests seem to work on master in Python 2 and Python 3.  If there's a blocking issue, maybe I can help.  Let me know.

**Comment by Varbin** [comment]
The current master is fully working under Python 3 (and 2). But thanks @chrisrossi . A release will be released in the next few days.
